# Generated by Django 6.0.6 on 2026-08-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, max_length=150, null=True, unique=True, verbose_name="Имя пользователя"
            ),
        ),
    ]
