# Generated by Django 6.0.6 on 2026-07-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="Введите заголовок записи", max_length=200, verbose_name="Заголовок"),
                ),
                ("content", models.TextField(help_text="Введите содержимое записи", verbose_name="Содержимое")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение для превью",
                        null=True,
                        upload_to="blog_previews/",
                        verbose_name="Превью (изображение)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Отметьте, чтобы опубликовать запись", verbose_name="Опубликовано"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Количество просмотров записи", verbose_name="Количество просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Блоговая запись",
                "verbose_name_plural": "Блоговые записи",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="blog_blogpo_created_2e77d7_idx"),
                    models.Index(fields=["is_published"], name="blog_blogpo_is_publ_c847aa_idx"),
                ],
            },
        ),
    ]
